### ISSUE TITLE
dist meta key does not contain the api value when api is set to 0

### ISSUE THREAD

**Issue by hythm7** [Raku/REA#1]
for example the below meta file "dist" is `App::CPAN:ver<0.0.1>:auth<cpan:TYIL>` while I think it should be `App::CPAN:ver<0.0.1>:auth<cpan:TYIL>:api<0>`

https://github.com/Raku/REA/blob/main/meta/A/App::CPAN/App::CPAN:ver%3C0.0.1%3E:auth%3Ccpan:TYIL%3E.json

**Comment by lizmat** [comment]
Generally, not specifying an `:api` is considered to be the same as specifying `:api<0>`.  To avoid possible name mismatches, everywhere where an `:api<0>` is specified in the meta, it is considered to not have been specified (and **imply** `:api<0>`).

Hope that makes sense?
