### ISSUE TITLE
p6doc should be removed

### ISSUE THREAD

**Issue by coke** [Raku/REA#10]
The installs corresponding to Raku/doc (in P/p6doc) should probably be removed.

Raku/doc repository hasn't been installable for some time, and if there is a version in here that is installable, the docs in it are very out of date (as is the probably broken build code); even when it was installed, it was using a version of the tools to read the docs that doesn't work that way anymore and is now in its own repo.

**Comment by lizmat** [comment]
I'm hesitant about removing distributions for historical reasons.  But I'm open to removing the META information, making it uninstallable until we have a better mechanism for dealing with this.  Would that work for you?

**Comment by lizmat** [comment]
So done as per 596ffbef2c2fbff8012c9fbb32a8a3fe6dd7ea79
