### ISSUE TITLE
source-url for some dists gives 404 Not Found

### ISSUE THREAD

**Issue by hythm7** [Raku/REA#2]
For some dists the `source-url` is incorrect, it has `.meta` extension instead of `.tar.gz`

For example `source-url` in the below META files: 
https://github.com/Raku/REA/blob/main/meta/T/TAP/TAP:ver%3C0.3.5%3E:auth%3Ccpan:LEONT%3E.json
https://github.com/Raku/REA/blob/main/meta/G/Gnome::N/Gnome::N:ver%3C0.19.5%3E:auth%3Ccpan:MARTIMM%3E.json

**Comment by lizmat** [comment]
Thank you for spotting this!

https://github.com/Raku/REA/commit/dd1d697dea4fc9d939197168279b027f928d54fe

The archiver now runs an updated version of `Ecosystem::Archive::Update` (not yet released), waiting for a CPAN distro getting updated to known 100% sure that the problem is fixed.
