### ISSUE TITLE
Versions are missing from the ecosystem

### ISSUE THREAD

**Issue by vrurg** [Raku/REA#4]
Either the indexer lags behind or missing module versions. The case I stumbled upon is about `Digest`. p6c currently has v0.5.0 of the module, but REA only knows about v0.4.0. From module's git log I assume that 0.5.0 was published on Feb 6, i.e. a month ago. Yet, REA repository was updated 12 days ago (https://github.com/Raku/REA/tree/main/meta/D/Digest) and the latest version is not there.

**Comment by lizmat** [comment]
Thanks for the spot!

Fixed with release 0.14 of [Ecosystem::Archive::Update](https://raku.land/zef:lizmat/Ecosystem::Archive::Update)

This affected *all* modules in the `p6c` ecosystem.  The fix added:

````
  Cairo:ver<0.3.0>:auth<github:timo>
  Config::TOML:ver<0.1.2>:auth<github:atweiden>
  Digest:ver<0.5.0>:auth<github:grondilu>
  Digest::SHA1::Native:ver<0.05>:auth<github:bduggan>
  GTK::Simple:ver<0.2.0>:auth<github:lizmat>
  HTTP::HPACK:ver<0.9.3>:auth<github:jnthn>
  Lingua::EN::Numbers:ver<2.8.2>:auth<github:thundergnat>
  Raku::Pod::Render:ver<3.7.2>:auth<github:finanalyst>
  Token::Foreign:ver<0.3.0>:auth<github:alabamenhu>
  raku-pod-extraction:ver<0.2.1>:auth<github:finanalyst>
  zef:ver<0.13.7>:auth<github:ugexe>
````
to the archive.
