### ISSUE TITLE
Test::Output  archive is not updated

### ISSUE THREAD

**Issue by hythm7** [Raku/REA#5]
It looks like `Test::Output:ver<1.001002>:auth<github:raku-community-modules>` archive doesn't match it's META6.json, the [META6](https://github.com/Raku/REA/blob/main/meta/T/Test::Output/Test::Output:ver%3C1.001002%3E:auth%3Cgithub:raku-community-modules%3E.json) has `resources` but the archive corresponding to that META6 file doesn't have `resources` directory:
```
> tar tf Test-Output-ver<1.001002>-auth<github-raku-community-modules>.tar.gz
Test-Output-master/
Test-Output-master/.gitignore
Test-Output-master/Changes
Test-Output-master/LICENSE
Test-Output-master/META6.json
Test-Output-master/README.md
Test-Output-master/_chromatin/
Test-Output-master/_chromatin/sub-signature.png
Test-Output-master/_chromatin/sub-usage-example.png
Test-Output-master/examples/
Test-Output-master/examples/output-test.t
Test-Output-master/lib/
Test-Output-master/lib/Test/
Test-Output-master/lib/Test/Output.pm6
Test-Output-master/logotype/
Test-Output-master/logotype/logo_32x32.png
Test-Output-master/t/
Test-Output-master/t/00-use.t
Test-Output-master/t/01-capture.t
Test-Output-master/t/02-Test.pm.t
Test-Output-master/xt/
Test-Output-master/xt/meta.t
```

This causes error when trying to install that module from the archive (using its corresponding META6 file).

(The project on github has `resources` direcctory)

**Comment by lizmat** [comment]
This shows **EXACTLY** the problem with the `p6c` ecosystem: people can update the distribution *without* changing the version.  The version is what *zef* and the *REA* use as an identification key.  If the version is the same, it will not download / upgrade.

I've bumped the version of `Test::Output` and an updated version *with* resources is now in the REA.

CC: @JJ
