### ISSUE TITLE
Can't install File::Directory::Tree on Windows

### ISSUE THREAD

**Issue by patrickbkr** [Raku/REA#6]
This is another variant of https://github.com/Raku/REA/issues/3. This time it's the `*` in the filename (caused by the `ver<*>` of that module). `*` is a forbidden character on Windows. The filename ends up being `File%3A%3ADirectory%3A%3ATree%3Aver%3C*%3E%3Aauth%3Cgithub%3Alabster%3E.tar.gz`. I guess obvious fix is to also % encode `*`s.

**Comment by lizmat** [comment]
We really shouldn't be having any module with `*` as version indicator  :-(

**Comment by patrickbkr** [comment]
Is [this](https://github.com/lizmat/Ecosystem-Archive-Update/blob/main/lib/Ecosystem/Archive/Update.rakumod#L97) the place where the replacements happen?
Can you just replace all traditionally forbidden chars?
According to [Wikipedia](https://en.wikipedia.org/wiki/Filename#Reserved_characters_and_words) those are `\/?*:|"<>`.

Of course also making sure to not have any `*`s in versions is a good measure to take as well.
