### ISSUE TITLE
Remove version of a distribution from REA

### ISSUE THREAD

**Issue by hythm7** [Raku/REA#9]
I need to remove `Pakku:ver<pupa>` from the index, because when initially created this version I was trying out different approaches, I did not think much about proper version thought I can easily remove or change later. and because that naively chosen version `pupa` shows higher than the version scheme I'm using now, it's causing some issues 
 (e.g. when I do want to upgrade).

I can't think of any harm will be done when removing that version, since the api changed long time ago and not working now. And by removal I mean removal from the [META.json](https://github.com/Raku/REA/blob/main/META.json) index so it can't be installed. the [archive](https://github.com/Raku/REA/blob/main/archive/P/Pakku/Pakku:ver%3Cpupa%3E:auth%3Cgithub:hythm7%3E.tar.gz) and [meta](https://github.com/Raku/REA/blob/main/meta/P/Pakku/Pakku:ver%3Cpupa%3E:auth%3Cgithub:hythm7%3E.json) should still be there.

Another option I can think of is to create may be `"deprecated": true` key in META file, to indicate that a version is deprecated and  should not be installed. but in the mean time can it be removed from the index until installation tooling support this new META file field.

**Comment by lizmat** [comment]
I have removed the META of Pakku from the REA for now with a9514bde43fe9e1e95bbb31da0d79d38696b75e9 and 7ebb77bf054c46b268699606c8eefb4e2f4c76d8

**Comment by lizmat** [comment]
Please close the issue if this fixes it for you.

**Comment by hythm7** [comment]
I have left a comment for the line that should not be removed. 

I need to remove one specific version, that is `pupa`, and leave the other version.

**Comment by lizmat** [comment]
Done with a2e58a4c848e8aaf0824fabd17fc4746e0c71e57

**Comment by hythm7** [comment]
Thank you!, and I do appreciate all the work you do for Raku.
